doc_fn = 'doc.txt'
toks_fn = 'tokens.pickle'
acts_fn = 'activations.npz'
contexts_fn = 'contexts.pickle'
knn_models_fn = 'knn_models.pickle'
knn_models_dirname = 'knn_models'
sphere_dir = 'sphere'
standard_dir = 'standard'
